### PR TITLE
Adding main_loop to the exports

### PR DESCRIPTION
**Pull request by joaomoa**
Can we add this function to the exports please? It's useful for me when I am already in an async context and don't want to start a new event loop, but only create a task to run tkinter

### CODE REVIEW

**Comment by insolor** [comment]
Ok, why not

**Comment by joaomoa** [comment]
Thanks for the speedy response

**Comment by insolor** [comment]
Can you describe your situation more? Do you run main_loop from an async function?

**Comment by joaomoa** [comment]
Exactly.
If I use `async_main_loop`, I get an error saying that the event loop is already running.

**Pull request merged**
